name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Pull Docker image
    - name: Pull Docker image
      run: docker pull mariamwafik333/fullstackspringbootangular_2:latest

    # Step 4: Deploy to EC2 via SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Pull the latest Docker image
          docker pull mariamwafik333/fullstackspringbootangular_2:latest
          
          # Stop any running containers
          docker stop $(docker ps -q) || true
          
          # Remove stopped containers to free up resources
          docker rm $(docker ps -aq) || true
          
          # Run the application container
          docker run -d -p 3000:3000 --name app mariamwafik333/fullstackspringbootangular_2:latest

